新增运营计划
@startuml
start
:创建运营计划;
:触发条件选择需触发;
:触发条件展示增加：有申请退单、有评价商品、
有评价店铺、有关注店铺、有分享商品、有分享商城、
有分享店铺、有分享赚、有邀请好友、有签到;
:保存计划;
stop
@enduml

新增运营计划埋点留存
@startuml
start
:将涉及到的新增触发条件通过canal将对应的表数据同步到统计业务表;
:根据选择的触发条件，统计关联对应的统计数据;
:统计结束将结果输出;
stop
@enduml

