自定义人群
@startuml
start
:新增自定义人群;
:选择对应的人群条件，包括：会员属性、会员行为以及会员标签,保存自定义人群信息;
:每天定时任务统计，按照一下步骤分步骤进行数据的聚合统计;
:1、会员基本信息统计;
:2、会员最近指标数据统计，将会员相关行为数据进行预统计;
:3、会员订单数据统计，将会员对应的订单数据进行预统计;
:4、自定义人群会员分组统计，根据选择的自定义人群条件进行汇总统计;
:5、自定义人群人数统计，将每个人群的总人数进行统计;
stop
@enduml