@startuml
start
partition 小程序/APP/PC/H5 {
        :选择参加营销活动的商品;
        :下单;
}
partition 定时任务 {
        :凌晨执行定时任务(marketingSituationJobHandler);
        :扫描优惠券活动明细表，汇总一条优惠券活动数据\n扫描拼团活动明细表，汇总一条拼团活动数据\n扫描秒杀活动明细表，汇总一条秒杀活动数据\n扫描预约活动明细表，汇总一条预约活动数据\n扫描预售活动明细表，汇总一条预售活动数据\n扫描减折赠活动明细表，汇总一条减折赠活动数据;
        :生成汇总数据表:\n营销活动数据概况天维度\n营销活动数据概况近7天维度\n营销活动数据概况近30天维度\n营销活动数据概况自然月维度;
}
partition 活动数据概况 {
        :不同时间范围内平台或商家的不同营销活动数据汇总;
}
stop
@enduml