-- 订单业绩明细表
CREATE TABLE `order_performance_detail` (
                                            `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
                                            `performance_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业绩ID（关联order_performance表）',
                                            `detail_type` tinyint NOT NULL COMMENT '明细类型（1-购买商品，2-退货商品）',
                                            `order_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '订单ID',
                                            `sku_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品SKU ID',
                                            `sku_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '商品名称',
                                            `sku_no` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '商品编号',
                                            `spec_details` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '规格详情',
                                            `school_level` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '学校级别（小学/中学）',
                                            `season` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '季节',
                                            `clothing_types` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '服装类型（多个，逗号分隔）',
                                            `quantity` int NOT NULL DEFAULT '1' COMMENT '数量',
                                            `unit_price` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '单价',
                                            `total_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '金额',
                                            `commission_amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '佣金金额',
                                            `return_order_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '退货单ID（退货时填写）',
                                            `agent_unique_code` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代理唯一码',
                                            `agent_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代理ID',
                                            `customer_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '客户ID',
                                            `remark` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
                                            `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                            `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                            PRIMARY KEY (`id`),
                                            KEY `idx_performance_id` (`performance_id`),
                                            KEY `idx_order_id` (`order_id`),
                                            KEY `idx_return_order_id` (`return_order_id`),
                                            KEY `idx_agent_id` (`agent_id`),
                                            KEY `idx_customer_id` (`customer_id`),
                                            KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单业绩明细表';