@startuml
start
:校验入参的必填;
:根据商品编码和店铺id批量获取商品SKU列表;
:提取skuId列表;
if(供应商?)then(yes)
    :根据skuId获取spuId;
    if(上架? and 商品库是否删除?) then (yes)
        :返回商品库不存在错误;
        stop;
    endif;
    :更新sku的上下架状态;
    :分析并更新spu的上下架以及部分上架状态;
    :同步关联商家商品的有效性;
    :同步供应商商品库的上下架状态;
    :同步供应商商品库的ES;
    :同步供应商商品和关联商家商品的ES;
else
    :更新sku的上下架状态;
    :分析并更新spu的上下架以及部分上架状态;
    :同步商品ES;
endif;
:上下架成功;
stop
@enduml