@startuml
start
:根据参数列表获取已过销售期的卡券id;
:将卡券商品参数列表按卡券分组，记录每个卡券需要发放的数量;
:根据卡券ID和指定的发放数量按销售期升序查询未删除、未发放的卡密;
while(参数列表有数据？)
    while(计数器<卡券发放数量？)
        partition 生成发货记录 {
            if(卡券和卡密有数据?)then(yes)
            :生成发放成功的记录;
            else if(卡券有数据并且卡密无数据？)
                if(该卡券已过销售期？) then(yes)
                    :生成过销售期的失败记录;
                else(no)
                    :生成无库存的失败记录;
                endif
            else(no)
                :生成其他原因的失败记录;
            endif
        }
    end while
end while
:订单填充卡密数据;
end
@enduml