@startuml
start
partition 确认订单{
    :设置默认会员等级价;
    if(当前会员是付费会员 && 商品所属商家、商品属于付费会员范围内?) then (yes)
        :计算商品折扣价，设置付费会员图标，消除原有普通等级价描述信息;
    endif
    :设置会员自定义价，回设普通会员等级价信息;
}

partition 提交订单{
    partition 计算付费会员价{
        :设置默认会员等级价;
        if(当前会员是付费会员 && 商品所属商家、商品属于付费会员范围内?) then (yes)
            :计算商品折扣价，设置付费会员图标，消除原有普通等级价描述信息;
        endif
        :设置会员自定义价，回设普通会员等级价信息;
    }

    partition 构建订单{
        :设置付费会员相关信息(付费会员等级id、付费记录id、付费商品ids);
    }

    partition 订单营销价格处理{
     :计算商品优惠金额;
    }

    partition 订单优惠券处理{
        :计算付费会员专属券优惠金额;
    }

    partition 订单价格处理{
        :付费优惠金额=商品优惠金额+专属优惠券优惠金额;
    }
}
end
@enduml