@startuml
start
if(当日是1号) then(yes)
    partition 每月1号发放 {
        :获取未删除、发放规则是按月发放的券礼包权益列表;
        while (data available?)
            :根据券礼包权益获取关联的普通会员等级和生效中的付费会员购买记录;
            :获取购买记录中的会员id;
            :根据普通会员等级查询普通会员;
            :查询权益配置的优惠券，组装券码数据;
            :批量保存券码数据;
        endwhile
    }
else (no)
    partition 每周发放 {
        :发放时间=计算当日属于周几;
        :获取未删除、发放规则是按周发放的券礼包权益;
            while (data available?)
                :根据券礼包权益获取关联的普通会员等级和生效中的付费会员购买记录;
                :获取购买记录中的会员id;
                :根据普通会员等级和会员升级时间查询普通会员;
                :查询权益配置的优惠券，组装券码数据;
                :批量保存券码数据;
            endwhile
    }
endif
end
@enduml
