apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elastic
    name: elastic-deployment
  name: elastic
  namespace: sbc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - image: {{IMAGE_NAME}}
          imagePullPolicy: Always
          name: elastic
          ports:
            - containerPort: 8850
              name: tomcat-port
          livenessProbe:
            httpGet:
              path: /act/health
              port: 8851
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          env:
            - name: JAVA_OPTS
              value: {{JAVA_ENV_PARAMS}}
            - name: NACOS_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: sbc-config
                  key: nacosAddress
            - name: RESTART_
              value: {{DATE}}
#          resources:
#            limits:
#              cpu: '1'
#              memory: 3Gi
#            requests:
#              cpu: '1'JAVA_ENV_PARAMS
#              memory: 3Gi
          volumeMounts:
            - mountPath: /data/server/log
              name: elastic-logs
      volumes:
        - name: elastic-logs
          hostPath:
            path: /data/sbc/logs/elastic
      hostNetwork: false
---